/// Declarative description of a looping ambient soundscape.
///
/// A recipe is a small signal graph made of three layer kinds:
///
/// * [NoiseLayer] – coloured noise (white / pink / brown) shaped by a filter
///   chain, optionally breathing with a slow LFO. This is the "bed" of almost
///   every natural sound (rain, wind, surf, fire, room tone).
/// * [ToneLayer] – sustained partials for drones and binaural carriers.
/// * [EventLayer] – randomly timed one-shots (drops, crackles, thunder, bird
///   chirps) generated by a Poisson process so the loop never audibly repeats.
///
/// The same recipe is rendered by two engines: `web/focus_audio.js` builds a
/// real-time Web Audio graph on the web, and `AmbientRenderer` renders an
/// offline stereo WAV on native platforms. Keeping the recipe data-driven keeps
/// both engines in sync and lets tests reason about every sound offline.
library;

enum NoiseColor { white, pink, brown }

enum AmbientFilterType { lowpass, highpass, bandpass }

class AmbientFilter {
  final AmbientFilterType type;
  final double frequency;
  final double q;

  const AmbientFilter.lowpass(this.frequency, {this.q = 0.707})
    : type = AmbientFilterType.lowpass;

  const AmbientFilter.highpass(this.frequency, {this.q = 0.707})
    : type = AmbientFilterType.highpass;

  const AmbientFilter.bandpass(this.frequency, {this.q = 1.0})
    : type = AmbientFilterType.bandpass;

  Map<String, Object> toJson() => {
    'type': type.name,
    'frequency': frequency,
    'q': q,
  };
}

/// Slow modulation applied to a layer.
///
/// Engines run two LFOs (at [rateHz] and `rateHz * 0.7317`) and sum them so the
/// movement never settles into an obvious period. [depth] is the amplitude
/// modulation depth (0 = static, 1 = fully ducks to silence);
/// [filterSweepHz] moves the last filter's cutoff by roughly ± that amount.
class AmbientLfo {
  final double rateHz;
  final double depth;
  final double filterSweepHz;

  const AmbientLfo({
    required this.rateHz,
    this.depth = 0.0,
    this.filterSweepHz = 0.0,
  });

  Map<String, Object> toJson() => {
    'rateHz': rateHz,
    'depth': depth,
    'filterSweepHz': filterSweepHz,
  };
}

class NoiseLayer {
  final NoiseColor color;
  final List<AmbientFilter> filters;
  final double gain;
  final AmbientLfo? lfo;

  /// 0 = mono, 1 = fully decorrelated left/right noise.
  final double width;

  /// -1 (left) .. 1 (right).
  final double pan;

  const NoiseLayer({
    required this.color,
    this.filters = const [],
    required this.gain,
    this.lfo,
    this.width = 0.8,
    this.pan = 0.0,
  });

  Map<String, Object?> toJson() => {
    'kind': 'noise',
    'color': color.name,
    'filters': filters.map((filter) => filter.toJson()).toList(),
    'gain': gain,
    'lfo': lfo?.toJson(),
    'width': width,
    'pan': pan,
  };
}

class TonePartial {
  final double ratio;
  final double gain;

  const TonePartial(this.ratio, this.gain);

  Map<String, Object> toJson() => {'ratio': ratio, 'gain': gain};
}

class ToneLayer {
  final double frequency;
  final List<TonePartial> partials;
  final double gain;

  /// When > 0 each partial is played by a detuned pair (± cents) for a slow
  /// chorus-like shimmer instead of a static, synthetic tone.
  final double detuneCents;
  final double tremoloRateHz;
  final double tremoloDepth;

  /// When > 0 the left ear hears [frequency] and the right ear
  /// `frequency + binauralBeatHz` (headphones required to perceive the beat).
  final double binauralBeatHz;
  final double pan;

  const ToneLayer({
    required this.frequency,
    this.partials = const [TonePartial(1, 1)],
    required this.gain,
    this.detuneCents = 0.0,
    this.tremoloRateHz = 0.0,
    this.tremoloDepth = 0.0,
    this.binauralBeatHz = 0.0,
    this.pan = 0.0,
  });

  Map<String, Object> toJson() => {
    'kind': 'tone',
    'frequency': frequency,
    'partials': partials.map((partial) => partial.toJson()).toList(),
    'gain': gain,
    'detuneCents': detuneCents,
    'tremoloRateHz': tremoloRateHz,
    'tremoloDepth': tremoloDepth,
    'binauralBeatHz': binauralBeatHz,
    'pan': pan,
  };
}

enum EventSound {
  /// A filtered noise burst (thunder, wave crash, crackle, gust, page flip).
  burst,

  /// A pitched blip made of sine partials (drip, chirp, clink, cricket).
  tone,
}

class EventLayer {
  final EventSound sound;

  /// Mean number of events per second (Poisson process).
  final double ratePerSecond;
  final double minGapSeconds;
  final double minDurationSeconds;
  final double maxDurationSeconds;

  /// Fraction of the event duration spent ramping up before the decay.
  final double attackRatio;
  final double gain;

  /// Random per-event attenuation: `gain * (1 - gainJitter * random)`.
  final double gainJitter;

  /// Random pan spread, 0 = centre only, 1 = anywhere in the stereo field.
  final double panSpread;

  /// Start frequency is drawn log-uniformly between these two values.
  final double minFrequency;
  final double maxFrequency;

  /// Frequency multiplier reached at the end of the event (filter cutoff for
  /// bursts, pitch glide for tones).
  final double sweepRatio;

  // Burst-only settings.
  final NoiseColor color;
  final AmbientFilterType filterType;
  final double q;

  // Tone-only settings.
  final List<TonePartial> partials;

  /// When > 0 the tone is chopped at this rate (cricket trill).
  final double trillHz;

  const EventLayer.burst({
    required this.ratePerSecond,
    this.minGapSeconds = 0.0,
    required this.minDurationSeconds,
    required this.maxDurationSeconds,
    this.attackRatio = 0.1,
    required this.gain,
    this.gainJitter = 0.5,
    this.panSpread = 0.6,
    required this.minFrequency,
    required this.maxFrequency,
    this.sweepRatio = 1.0,
    this.color = NoiseColor.white,
    this.filterType = AmbientFilterType.bandpass,
    this.q = 1.0,
  }) : sound = EventSound.burst,
       partials = const [],
       trillHz = 0.0;

  const EventLayer.tone({
    required this.ratePerSecond,
    this.minGapSeconds = 0.0,
    required this.minDurationSeconds,
    required this.maxDurationSeconds,
    this.attackRatio = 0.02,
    required this.gain,
    this.gainJitter = 0.5,
    this.panSpread = 0.6,
    required this.minFrequency,
    required this.maxFrequency,
    this.sweepRatio = 1.0,
    this.partials = const [TonePartial(1, 1)],
    this.trillHz = 0.0,
  }) : sound = EventSound.tone,
       color = NoiseColor.white,
       filterType = AmbientFilterType.bandpass,
       q = 1.0;

  Map<String, Object> toJson() => {
    'kind': 'event',
    'sound': sound.name,
    'ratePerSecond': ratePerSecond,
    'minGapSeconds': minGapSeconds,
    'minDurationSeconds': minDurationSeconds,
    'maxDurationSeconds': maxDurationSeconds,
    'attackRatio': attackRatio,
    'gain': gain,
    'gainJitter': gainJitter,
    'panSpread': panSpread,
    'minFrequency': minFrequency,
    'maxFrequency': maxFrequency,
    'sweepRatio': sweepRatio,
    'color': color.name,
    'filterType': filterType.name,
    'q': q,
    'partials': partials.map((partial) => partial.toJson()).toList(),
    'trillHz': trillHz,
  };
}

class AmbientRecipe {
  final List<NoiseLayer> noise;
  final List<ToneLayer> tones;
  final List<EventLayer> events;

  /// Final trim so every soundscape sits at a comparable loudness.
  final double masterGain;

  const AmbientRecipe({
    this.noise = const [],
    this.tones = const [],
    this.events = const [],
    this.masterGain = 1.0,
  });

  Map<String, Object> toJson() => {
    'masterGain': masterGain,
    'layers': [
      ...noise.map((layer) => layer.toJson()),
      ...tones.map((layer) => layer.toJson()),
      ...events.map((layer) => layer.toJson()),
    ],
  };
}
